### ISSUE TITLE
problem with dependency handling

### ISSUE THREAD

**Issue by eMBee** [dalehenrich/filetree#142]
i can't pin down the the issue yet, but it seems to be a problem git filetree handling packages with dependencies:

i created a new meta-package which depends on a few other packages. most of those were new too, but one was an existing package. aside from the fact that this existing package got committed in its entirety (which is hard to avoid because we would need a git history for it otherwise), for the meta-package an entry was created, listing all the other packages as dependencies using the version-names as created by monticello.

git filetree renumbers those version-names to start from 1. for the new packages that was fine because they are already 1, but for the existing package, monticello created a new version 97.  git filetree turns that into version 1, and when i try to load the meta-package it fails because monticello is looking for version 97.

not sure how this should be solved.
does git filetree know about dependencies yet? 
as far as i can tell, it only tracks ancestors per package. but if multiple packages are committed to the same repo, no dependency is created among them, even though git itself implies a dependency.

maybe dependencies could be modeled by committing each package into a separate branch and the meta-package as a merge-commit. the dependencies would then be all the parents of that commit.

this may not be enough though, because it wasn't until i unloaded the meta-package, fixed the version number and then loaded the fixed package that the error about not finding version 97 went away. though it may have to do with the commit-ids not being updated, so that monticello didn't recognize the change.

**Comment by ThierryGoubier** [comment]
Well, I haven't worked with dependencies much, so you're catching something there and your idea of a solution looks nice. I already put some code to update the commit-ids, but not the git-extracted version number (as you point out, it is different from the Monticello given one).

My idea would be, to solve that, to consider that the following holds true in Monticello:
- Saving a package with dependencies save this package and its dependencies in the same repository (even if the package isn't dirty? Then need to ensure git-managed packages have their correct version number as well, which would solve most issues with dependencies)

Now the solution would be, when saving the meta-package, to have the git filetree repository switch to a special, one commit for many packages mode, and a similar mode upon loading (use commit id from meta-package instead of looking for the version number).

Why? Because, when cloning a git repository, one can always limit the depth and therefore change the version numbers (or even have commits disappearing...). git clone --depth 1 is particularly interesting for that.

I'll look into both ideas:
- better backport of git-generated version numbers into the package ancestry inside the image (should cure the dependencies issue as a first step).
- change git filetree so that meta packages + dependencies are considered as a single commit upon saving and loading.

**Comment by eMBee** [comment]
Excerpts from Thierry Goubier's message of 2015-02-02 07:12:03 +0100:

> Well, I haven't worked with dependencies much, so you're catching something there and your idea of a solution looks nice. I already put some code to update the commit-ids, but not the git-extracted version number (as you point out, it is different from the Monticello given one).
> 
> My idea would be, to solve that, to consider that the following holds true in Monticello:
> - Saving a package with dependencies save this package and its dependencies
>   in the same repository (even if the package isn't dirty? Then need to ensure
>   git-managed packages have their correct version number as well, which would
>   solve most issues with dependencies)

in my case the package was dirty. which is why i added it in the first place.
the problem is that dependency information is saved in 
meta.package.package/monticello.meta/dependencies and git-filetree is not
replacing that information.

after i replaced it manually, things started to work.

> Now the solution would be, when saving the meta-package, to have the git filetree repository switch to a special, one commit for many packages mode, and a similar mode upon loading (use commit id from meta-package instead of looking for the version number).
> 
> Why? Because, when cloning a git repository, one can always limit the depth and therefore change the version numbers (or even have commits disappearing...). git clone --depth 1 is particularly interesting for that.

but that would require a new clone each time a package is loaded. and i don't
see how that solves the problem.

all packages would appear as version 1, but, even now, they do appear as
version 1 already even as independent commits. that is, it appears that for
each package the code already only counts the commits that touch that package.

so if the point here is to get a reliable version number, that's already working.

the only thing that would need to be changed is, how the meta package is saved.
it appears that currently, the meta-package is saved first, and the
dependencies follow. 

if the meta-package was saved last, the code could just look for the latest
commit of each package before the meta-package, and pick the version from that.

**Comment by ThierryGoubier** [comment]
> in my case the package was dirty. which is why i added it in the first place. the problem is that dependency information is saved in meta.package.package/monticello.meta/dependencies and git-filetree is not replacing that information. after i replaced it manually, things started to work.

Yes, I understood that. But propagating the correct, git generated version number isn't enough. Since the git-generated version number depends on the depth of the history, then this version number may change if the history is shortened, which is the case with git clone --depth N.

> but that would require a new clone each time a package is loaded.

No, not a clone,  but a single commit for multiple packages when writing to the repository (1), and reading all the dependent packages from the same commit ID (2).

> and i don't see how that solves the problem. all packages would appear as version 1, but, even now, they do appear as version 1 already even as independent commits. that is, it appears that for each package the code already only counts the commits that touch that package. so if the point here is to get a reliable version number, that's already working. the only thing that would need to be changed is, how the meta package is saved. it appears that currently, the meta-package is saved first, and the dependencies follow. if the meta-package was saved last, the code could just look for the latest commit of each package before the meta-package, and pick the version from that.

Yes! This would be the idea more or less. With (1), git filetree would delay the commit until all the dependencies and the meta-package have been written to disk (in whatever order, it wouldn't matter), and, with (2), a similar mode would disregard version information for the dependencies and use the same commit ID to load all the packages (meta + dependencies).

Now, I need to study the Monticello code if I can get that to work without modifying Monticello itself.

**Comment by eMBee** [comment]
Excerpts from Thierry Goubier's message of 2015-02-02 10:35:26 +0100:

> propagating the correct, git generated version number isn't enough. Since the git-generated version number depends on the depth of the history, then this version number may change if the history is shortened, which is the case with git clone --depth N.

i misunderstood what you meant with the clone command. i thought you
wanted to use it to help get matching version numbers.

> Yes! This would be the idea more or less. With (1), git filetree would delay the commit until all the dependencies and the meta-package have been written to disk (in whatever order, it wouldn't matter), and, with (2), a similar mode would disregard version information for the dependencies and use the same commit ID to load all the packages (meta + dependencies).

ah, yes, in a single commit the order does not matter. it's either that or
forcing the ordering to commit the meta-package last.

**Comment by ThierryGoubier** [comment]
Hi @dalehenrich, I'm nearing a solution to solve this, but it would change the way packages with dependencies are stored (as they would be visible to git, not to filetree).

Where should/could I add a git related property file in the filetree arborescence? In the monticello.meta/ subdirectory?

**Comment by dalehenrich** [comment]
Do you have some code I could look at?

I'm not sure what you mean by "visible to git, not filetree".... 

Package dependencies are a purely Monticello mechanism and from that perspective the dependency info should go into monticello.meta. Yet another thing that will need auto-merge support:)

**Comment by ThierryGoubier** [comment]
I'll push something on this branch when I have something green.

**Comment by ThierryGoubier** [comment]
Ok @dalehenrich , here it goes ( b0e0e0dc2622c677da5fde762d26b927e151d32a ).

Handle previous and new style dependencies storing. Should improve things in MCResolvedVersionDependency, and maybe look at some caching. Tell me what do you think.

**Comment by dalehenrich** [comment]
@ThierryGoubier, in reviewing the code, it looks like Filetree was already writing and reading dependency info and the dependency inform should be written to the monticello.meta directory (dependency subdirectory)... when I saw this bug, I thought that perhaps Filetree also suffered from a problem since I don't use dependencies that much ... looking at your fix it pretty much look like you are doing the work at the gitfiletree level ... which is fine ... I suppose I should add a test case and make sure that the mechanism at least works in filetree ... thanks!

**Comment by ThierryGoubier** [comment]
Hi @eMBee , @dalehenrich , can you try the latest version? It implements the single commit idea and handle previous repositories with dependencies, as well as the various ways dependencies are saved.

All tests are green, but more exposure is better. Loading it in Pharo3.0 with the following should work:

``` smalltalk
Metacello new
  baseline: 'FileTree';
  repository: 'github://dalehenrich/filetree:issue_142/repository';
  load: 'Git'.
```

**Comment by ThierryGoubier** [comment]
branch issue_142 was merged into pharo3.0_dev
